/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test.cprl.gui;

import com.formdev.flatlaf.FlatDarkLaf;
import edu.citadel.compiler.Compiler;
import edu.citadel.cvm.CVM;
import edu.citadel.cvm.assembler.Assembler;
import edu.citadel.cvm.assembler.ast.Instruction;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import test.cprl.TestUtils;

/**
 *
 * @author David
 */
public class JanelaTestesCompilacaoExecucao extends javax.swing.JFrame {

    private CVM vm;
    
    /**
     * Creates new form JanelaTestesCompilacaoExecucao
     */
    public JanelaTestesCompilacaoExecucao() {
        
        initComponents();
        
        DefaultComboBoxModel<String> m = (DefaultComboBoxModel<String>) comboArquivoTeste.getModel();
        
        for ( String t : TestUtils.caminhosFontes ) {
            m.addElement( t );
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelArquivosTeste = new javax.swing.JPanel();
        lblArquivoTeste = new javax.swing.JLabel();
        comboArquivoTeste = new javax.swing.JComboBox<>();
        btnVaiArquivoTeste = new javax.swing.JButton();
        painelArquivosGenericos = new javax.swing.JPanel();
        lblArquivoGenerico = new javax.swing.JLabel();
        txtArquivoGenerico = new javax.swing.JTextField();
        btnEscolherArquivoGenerico = new javax.swing.JButton();
        btnVaiArquivoGenerico = new javax.swing.JButton();
        painelObservacoes = new javax.swing.JPanel();
        scrollObservacoes = new javax.swing.JScrollPane();
        areaObservacoes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Testes de Compilação e Execução");

        painelArquivosTeste.setBorder(javax.swing.BorderFactory.createTitledBorder("Construir e Executar Arquivos de Teste"));

        lblArquivoTeste.setText("Arquivo de Código Fonte:");

        btnVaiArquivoTeste.setText("Vai!");
        btnVaiArquivoTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaiArquivoTesteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelArquivosTesteLayout = new javax.swing.GroupLayout(painelArquivosTeste);
        painelArquivosTeste.setLayout(painelArquivosTesteLayout);
        painelArquivosTesteLayout.setHorizontalGroup(
            painelArquivosTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelArquivosTesteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelArquivosTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelArquivosTesteLayout.createSequentialGroup()
                        .addComponent(lblArquivoTeste)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboArquivoTeste, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelArquivosTesteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVaiArquivoTeste)))
                .addContainerGap())
        );
        painelArquivosTesteLayout.setVerticalGroup(
            painelArquivosTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelArquivosTesteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelArquivosTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArquivoTeste)
                    .addComponent(comboArquivoTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVaiArquivoTeste)
                .addContainerGap())
        );

        painelArquivosGenericos.setBorder(javax.swing.BorderFactory.createTitledBorder("Construir e Executar Arquivos Genéricos"));

        lblArquivoGenerico.setText("Arquivo de Código Fonte:");

        txtArquivoGenerico.setEditable(false);

        btnEscolherArquivoGenerico.setText("...");
        btnEscolherArquivoGenerico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscolherArquivoGenericoActionPerformed(evt);
            }
        });

        btnVaiArquivoGenerico.setText("Vai!");
        btnVaiArquivoGenerico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaiArquivoGenericoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelArquivosGenericosLayout = new javax.swing.GroupLayout(painelArquivosGenericos);
        painelArquivosGenericos.setLayout(painelArquivosGenericosLayout);
        painelArquivosGenericosLayout.setHorizontalGroup(
            painelArquivosGenericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelArquivosGenericosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelArquivosGenericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelArquivosGenericosLayout.createSequentialGroup()
                        .addComponent(lblArquivoGenerico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArquivoGenerico, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEscolherArquivoGenerico))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelArquivosGenericosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVaiArquivoGenerico)))
                .addContainerGap())
        );
        painelArquivosGenericosLayout.setVerticalGroup(
            painelArquivosGenericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelArquivosGenericosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelArquivosGenericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArquivoGenerico)
                    .addComponent(txtArquivoGenerico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEscolherArquivoGenerico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVaiArquivoGenerico)
                .addContainerGap())
        );

        painelObservacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Observações"));

        areaObservacoes.setEditable(false);
        areaObservacoes.setColumns(20);
        areaObservacoes.setLineWrap(true);
        areaObservacoes.setRows(5);
        areaObservacoes.setText("- Ao escolher um arquivo de código fonte da CPRL e clicar no botão \"Vai!\", o compilador será invocado\npara gerar o código e, caso não haja nenhum erro, o assembler usará o código gerado para montar o\narquivo de código objeto que, por sua vez, será executado pela CVM.\n- A saída da execução se dará pela janela de saída do NetBeans.");
        scrollObservacoes.setViewportView(areaObservacoes);

        javax.swing.GroupLayout painelObservacoesLayout = new javax.swing.GroupLayout(painelObservacoes);
        painelObservacoes.setLayout(painelObservacoesLayout);
        painelObservacoesLayout.setHorizontalGroup(
            painelObservacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelObservacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollObservacoes)
                .addContainerGap())
        );
        painelObservacoesLayout.setVerticalGroup(
            painelObservacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelObservacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollObservacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelArquivosTeste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelArquivosGenericos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelObservacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelArquivosTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelArquivosGenericos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelObservacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVaiArquivoTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaiArquivoTesteActionPerformed
        compilarMontarExecutar( comboArquivoTeste.getSelectedItem().toString() );
    }//GEN-LAST:event_btnVaiArquivoTesteActionPerformed

    private void btnVaiArquivoGenericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaiArquivoGenericoActionPerformed
        compilarMontarExecutar( txtArquivoGenerico.getText() );
    }//GEN-LAST:event_btnVaiArquivoGenericoActionPerformed

    private void btnEscolherArquivoGenericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolherArquivoGenericoActionPerformed
        
        JFileChooser fc = new JFileChooser( "." );
        fc.setFileFilter( new FileNameExtensionFilter( "Arquivo de Código Fonte da CPRL", "cprl" ) );
        fc.setDialogTitle( "Abrir" );
        fc.setMultiSelectionEnabled( false );
        
        if ( fc.showOpenDialog( this ) == JFileChooser.APPROVE_OPTION ) {
            File f = fc.getSelectedFile();
            txtArquivoGenerico.setText( f.getAbsolutePath() );
        }
        
    }//GEN-LAST:event_btnEscolherArquivoGenericoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        
        try {
            UIManager.setLookAndFeel( new FlatDarkLaf() );
        } catch( Exception ex ) {
        }
        
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                new JanelaTestesCompilacaoExecucao().setVisible( true );
            }
        });
        
    }

    private void compilarMontarExecutar( String caminho ) {

        try {

            caminho = caminho.replace( ".cprl", "" );

            Compiler c = new Compiler( new File( caminho + ".cprl" ) );
            c.compile();

            Assembler a = new Assembler( new File( caminho + ".asm" ) );
            a.assemble();

            FileInputStream o = new FileInputStream( new File( caminho + ".obj" ) );

            Instruction.resetMaps();
            CVM vm = new CVM( 8192 ); // 8KB de memória
            vm.loadProgram( o );
            vm.run();

        } catch ( IOException exc ) {
            JOptionPane.showMessageDialog( 
                    null, 
                    exc.getMessage(), 
                    "ERRO", 
                    JOptionPane.ERROR_MESSAGE );
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaObservacoes;
    private javax.swing.JButton btnEscolherArquivoGenerico;
    private javax.swing.JButton btnVaiArquivoGenerico;
    private javax.swing.JButton btnVaiArquivoTeste;
    private javax.swing.JComboBox<String> comboArquivoTeste;
    private javax.swing.JLabel lblArquivoGenerico;
    private javax.swing.JLabel lblArquivoTeste;
    private javax.swing.JPanel painelArquivosGenericos;
    private javax.swing.JPanel painelArquivosTeste;
    private javax.swing.JPanel painelObservacoes;
    private javax.swing.JScrollPane scrollObservacoes;
    private javax.swing.JTextField txtArquivoGenerico;
    // End of variables declaration//GEN-END:variables
}
